FROM ubuntu:16.04

RUN apt-get update -y && \
apt-get install -y moreutils net-tools libaio1 wget gettext-base && \
cd tmp && wget https://dev.mysql.com/get/Downloads/MySQL-Cluster-7.4/mysql-cluster-gpl-7.4.16-debian7-x86_64.deb && \
dpkg -i mysql-cluster-gpl-7.4.16-debian7-x86_64.deb

COPY config.ini /var/lib/mysql-cluster/
COPY start-cluster.sh /opt/mysql/server-5.6/bin/
CMD /opt/mysql/server-5.6/bin/start-cluster.sh

