FROM ubuntu:16.04

RUN apt-get update -y && \
apt-get install -y net-tools libaio1 libnuma1 libdata-dumper-simple-perl  wget && \
cd tmp && wget https://dev.mysql.com/get/Downloads/MySQL-Cluster-7.4/mysql-cluster-gpl-7.4.16-debian7-x86_64.deb && \
dpkg -i mysql-cluster-gpl-7.4.16-debian7-x86_64.deb 

RUN groupadd mysql && \
useradd -r -g mysql -s /bin/false mysql && \
cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql && \ 
mkdir -p /var/lib/mysql-files

RUN /opt/mysql/server-5.6/scripts/mysql_install_db --user=mysql

COPY my.cnf /etc/my.cnf

CMD [ "/opt/mysql/server-5.6/bin/mysqld_safe" ]
